/**
 * Writes dist/config.js (and public/config.js) from process env so production
 * `start:web` can point at the API without rebuilding the JS bundle.
 *
 * Reads (in order of preference):
 *   VITE_API_URL / API_URL
 *   VITE_WS_URL  / WS_URL
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = join(here, "..");

const apiUrl = (
  process.env.VITE_API_URL ||
  process.env.API_URL ||
  ""
).replace(/\/$/, "");

const wsUrl = (
  process.env.VITE_WS_URL ||
  process.env.WS_URL ||
  (apiUrl
    ? apiUrl.replace(/^http/, "ws") // http→ws, https→wss
    : "")
).replace(/\/$/, "");

const body = `// Generated by scripts/write-runtime-config.ts — do not edit by hand
window.__NANOCORE_CONFIG__ = ${JSON.stringify(
  { apiUrl, wsUrl },
  null,
  2,
)};
`;

const targets = [
  join(webRoot, "public", "config.js"),
  join(webRoot, "dist", "config.js"),
];

for (const file of targets) {
  const dir = dirname(file);
  if (file.includes(`${join("dist")}`) && !existsSync(join(webRoot, "dist"))) {
    console.warn(
      "[write-runtime-config] dist/ missing — run build:web first if you need production serve",
    );
    continue;
  }
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(file, body, "utf8");
  console.log(`[write-runtime-config] wrote ${file}`);
}

if (apiUrl || wsUrl) {
  console.log(`[write-runtime-config] apiUrl=${apiUrl || "(empty)"} wsUrl=${wsUrl || "(empty)"}`);
} else {
  console.log(
    "[write-runtime-config] no VITE_API_URL/VITE_WS_URL — client will use same-origin / defaults",
  );
}
